### ISSUE TITLE
开屏广告退出动画可以自定义吗？

### ISSUE THREAD

**Issue by lianfanghua** [FlutterAds/flutter_pangle_ads#12]
在接入开屏广告后，退出动画为向下滑出屏幕（iOS），这个动画在开屏广告上显得不太友好（滑出过程空白部分为白屏），是否能自定义或者把广告取消呢？

**Comment by lianfanghua** [comment]
> > > 对于问题1和问题2，建议在程序启动后单独去判断是否需要展示广告，开屏比较特殊，看你目前的状态是在 `initState` 中初始化的并且显示的广告，建议在 `runApp` 之前就初始化广告，但是这里走异步不要同步，不然会卡 Flutter 容器的初始化
> 
> > 
> 
> > 这里也是有原因的，因为工信部要求必须用户同意隐私政策后，其他东西才允许初始化，所以用户首次使用，是有一个确认弹窗，用户确认后，才开始初始化的。
> 
> > 
> 
> > 这部分逻辑我都是在闪屏页进行的，闪屏页打开，判断本地缓存是否已同意隐私政策，同意的话开始加载广告及其他初始化，否则的话就退出程序。
> 
> 
> 
> 我们也是有这个逻辑，但是如果没有登录就说明没有必要展示广告（首次就展示广告体验也不好），登录信息存在缓存信息，判断是否有缓存信息在初始化和UI以及操作是没有关系的

逻辑是类似的，但问题在于就像我录制的视频，没广告会白屏，体验不太好，我在考虑能不能用另外一个页面包装广告，等到广告加载成功再通知显示，不过这样势必增加业务复杂性

**Comment by huntrist** [comment]
> > 但是点击广告弹出详情页后，返回到广告页，倒计时卡死是什么问题呢？
> 
> 这个我周末会排查解决

这个有进展么？有大神知道是什么原因么？

**Comment by yy1300326388** [comment]
暂时没有排查呢

**Comment by BytesZero** [comment]
暂时关闭
