### ISSUE TITLE
有用户反馈ipad的全屏视频广告没有关闭按钮

### ISSUE THREAD

**Issue by ghostgzt** [FlutterAds/flutter_pangle_ads#15]
有用户反馈ipad的全屏视频广告没有关闭按钮，广告无法关闭，这是bug么？怎样处理？

![4ce1bbe5c4ce0b32cc2355bbde175043_960e088396f04112b7fb76b0c0792b4e](https://user-images.githubusercontent.com/4105507/144788636-6e959213-226d-4196-a19e-044a721cb678.jpeg)

**Comment by yy1300326388** [comment]
可以尝试升级一下 iOS 依赖版本

**Comment by ghostgzt** [comment]
> 可以尝试升级一下 iOS 依赖版本

Ads-CN已经是4.1.0.2版本了

**Comment by yy1300326388** [comment]
那可以给官方反馈一下 https://github.com/bytedance/Bytedance-UnionAD

**Comment by yy1300326388** [comment]
暂时关闭啦，只能等待官方修复
