### ISSUE TITLE
banner一直报错40006

### ISSUE THREAD

**Issue by fuufuuf** [FlutterAds/flutter_pangle_ads#19]
请问下，banner的初始化是在哪里完成的？

我看其他的广告位通过PangleAds(appId)可以对应的appId,直接引入posId就能正常展示。但是banner直接传入的是posId,这个版位的appId是哪里初始化的呢

我在想是不是报错和初始化banner有关系，因为我用了事例的appId和posId是没有问题的。

**Comment by yy1300326388** [comment]
Appid是在启动的时候初始化，Banner和其他一样只需要传入posid即可

**Comment by yy1300326388** [comment]
有问题再提问开启
