### ISSUE TITLE
Property 'splashButtonType' not found on object of type 'BUAdSlot *'

### ISSUE THREAD

**Issue by logos-flutter** [FlutterAds/flutter_pangle_ads#20]
![image](https://user-images.githubusercontent.com/10265851/157581341-73188cf9-15e3-4f64-b0a2-165870c79f96.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.2 21D49 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.2)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

集成的版本 ：flutter_pangle_ads: ^2.4.0 # Null Safety

xcode版本 ： Version 13.2.1 (13C100)

**Comment by yy1300326388** [comment]
可能需要降低版本了，我优化一下

**Comment by yy1300326388** [comment]
这里的版本是只穿山甲SDK版本

**Comment by logos-flutter** [comment]
> 这里的版本是只穿山甲SDK版本

现在穿山甲的哪个版本能运行起来，我尝试了几个版本，都有问题，比如4.2.5.6

**Comment by yy1300326388** [comment]
我看看我本地的版本，发给你先用

**Comment by yy1300326388** [comment]
@logos-flutter  我当前本地是 `4.1.0.2` 版本

**Comment by joe-lz** [comment]
何时能更新解决呢 @yy1300326388

**Comment by yy1300326388** [comment]
@joe-lz  正在解决了，今天更新

**Comment by yy1300326388** [comment]
@joe-lz @logos-flutter  目前等待 CI 自动测试完毕就可以发布啦

**Comment by yy1300326388** [comment]
@joe-lz @logos-flutter  已修复 [`v2.5.0` ](https://pub.dev/packages/flutter_pangle_ads)
