### ISSUE TITLE
信息流广告出现频繁弹出的问题

### ISSUE THREAD

**Issue by rockingdice** [FlutterAds/flutter_pangle_ads#27]
用的是最新版本2.5.0

附件为用户提供的视频。

信息流广告并不在这个页面上，而是之前的页面，是我处理的哪里不对导致的吗？

离开之前的信息流页面要做什么特别的处理吗？

还有文档上提到要清除adsid，什么时候清除更好呢？

麻烦解答一下~

https://user-images.githubusercontent.com/3458134/177278604-575fac08-bf7d-4162-90d7-732e271ff26b.mp4

**Comment by yy1300326388** [comment]
只有触发了点击才会弹出，是因为你没有销毁吧

**Comment by yy1300326388** [comment]
你是 Widget 这层没有销毁，可以设置 `AdFeedWidget`中的`show=false`

**Comment by yy1300326388** [comment]
`clearFeedAd` 是清除原生侧的信息流广告，退出页面需要调用

**Comment by rockingdice** [comment]
@yy1300326388 感谢解答，确实不太清楚show这个参数是做这个用的。我的app里页面Navigator是自己写的，即使页面切换了，其实还保留在Offscreen里，可能是这个原因广告还存在屏幕上导致用户误点。
想问一下如果广告滑出屏幕外了，还有可能让用户点开广告吗？因为位置已经不在屏幕内了。目前反馈问题的全部是iOS用户。
谢谢！
