### ISSUE TITLE
请问如何支持深色及浅色主题？

### ISSUE THREAD

**Issue by zeewell** [FlutterAds/flutter_pangle_ads#28]
目前遇到的问题：

有Logo的开屏广告页面，如何能够支持深色或浅色主题（下方Logo区域的背景色会不同）？又如何根据不同的主题自动选择不同的Logo（色彩的明亮度可能不同）呢？

想请教下应该怎么支持呢？

**Comment by yy1300326388** [comment]
大概明白你的意思了，可否来两张图片确认一下

**Comment by zeewell** [comment]
如果 #29 这个可以实现的话，那么这个 issue 可以不要了。通过自定义就可以实现想要的功能。

**Comment by yy1300326388** [comment]
对的，目前我初步理解你更换logo 即可，logo 铺平整个底部即可，现在就是支持的，看你的logo 怎么设计了

**Comment by yy1300326388** [comment]
相同问题 https://github.com/FlutterAds/flutter_pangle_ads/issues/11

**Comment by zeewell** [comment]
> 对的，目前我初步理解你更换logo 即可，logo 铺平整个底部即可，现在就是支持的，看你的logo 怎么设计了

是的，你说的方法，基本上可以实现。
但如果把整个渲染放慢显示的话，会发现广告所在的位置会先出现白屏再出现广告，如果此时是暗黑模式的话，其实也是有问题的。当然如果不放慢正常显示的话，可以忽略这个问题。

**Comment by zeewell** [comment]
所以，我还是觉得 #11 这个挺重要的。这个实现后，也可以基于此实现目前库里的效果（并且还能支持主题的切换）。
