### ISSUE TITLE
有没有可能将Splash广告封装成一个独立的Widget？

### ISSUE THREAD

**Issue by zeewell** [FlutterAds/flutter_pangle_ads#29]
Hi，有没有可能将Splash广告封装成一个独立的Widget呢？这样的话就能自定义开屏广告展示界面的布局和样式。

**Comment by yy1300326388** [comment]
是的，可以的

**Comment by zeewell** [comment]
目前版本能实现吗？如果不能的话，请问有支持的计划吗？特别想要这个feature，还是非常有价值的。

**Comment by yy1300326388** [comment]
实现不难，重点在于优化，预计是会在下个开屏的大版本支持，我也特别想要个 Star，对我非常有帮助，谢谢

**Comment by yy1300326388** [comment]
相同问题：https://github.com/FlutterAds/flutter_pangle_ads/issues/11
