### ISSUE TITLE
开屏广告添加超时参数设置 showSplashAd 

### ISSUE THREAD

**Issue by yy1300326388** [FlutterAds/flutter_pangle_ads#3]
现在是默认时间 3.5秒，需要提供超时的参数

**Comment by yy1300326388** [comment]
已在 develop 分支合并，等待发布🚀

**Comment by yy1300326388** [comment]
已发布 `v1.2.0` | `v2.2.0 ` 版本，相关变更如下：
- 本次添加了超时时间设置 `timeout` ，在Flutter 接口上统一时间为秒，iOS 原生端为秒，Android 原生端转换为毫秒。
- 本次接口有较大变化，logo 参数由位置参数变为可选命名参数，API 发生轻微变化，请更新适配即可，操作如下。
### 原本调用
``` Dart
FlutterPangleAds.showSplashAd(posId, 'flutterads_logo');
```
### 现在调用
``` Dart
FlutterPangleAds.showSplashAd(posId, logo:'flutterads_logo');
```

**Comment by SheepYang1993** [comment]
@yy1300326388 ios的开屏log是怎么设置的啊？
怎么看要用什么路径？

**Comment by yy1300326388** [comment]
@SheepYang1993 
请认真看这个文档和参考demo https://github.com/FlutterAds/flutter_qq_ads/blob/develop/doc/SETTING_LOGO.md
