### ISSUE TITLE
穿山甲SDK4700版本开屏广告接入方式变更

### ISSUE THREAD

**Issue by yy1300326388** [FlutterAds/flutter_pangle_ads#30]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/8764899/179171719-cfe3ae54-8fcc-4cb8-9e77-08834ada1f32.png">

iOS：https://bytedance.feishu.cn/docx/doxcnV1VwoLFniTJn7FwFFM9rte

Android：https://bytedance.feishu.cn/docx/doxcnS0ykd2WhBwAFxwEODRuBYf

**Comment by mifeng9999** [comment]
真的是太棒了！作者大佬是跟着官方更新，牛，Star！

**Comment by mifeng9999** [comment]
大佬问下，4700什么时间更新呀？^_^^_^

**Comment by yy1300326388** [comment]
等官方出来，稳定后

**Comment by yy1300326388** [comment]
iOS 已更新，但 Android 还没出来，等都出来稳定后会更新

**Comment by mifeng9999** [comment]
感谢无私分享，坐等更新。

**Comment by cunwaitaoshu** [comment]
android 也更新了

**Comment by yy1300326388** [comment]
近期会更新一个版本

**Comment by cunwaitaoshu** [comment]
感谢辛苦付出

> 近期会更新一个版本

感谢辛苦付出

**Comment by yy1300326388** [comment]
Android 的依赖还没更新，暂时不做更新，https://artifact.bytedance.com/repository/pangle/com/pangle/cn/ads-sdk-pro/

<img width="932" alt="image" src="https://user-images.githubusercontent.com/8764899/184051250-2dce6f5e-41ab-4414-b479-bc5daea6c8b4.png">

**Comment by yy1300326388** [comment]
预计月底更新

**Comment by yy1300326388** [comment]
本地 SDK Android 已更新，等待远程依赖更新后，立马更新上去

**Comment by yy1300326388** [comment]
开屏广告将分为一下三个节奏进行重构
- 升级 4700 接口
- 增加点睛功能
- 增加卡片功能

**Comment by yy1300326388** [comment]
Android 已升级完毕，等待官方远程依赖更新

**Comment by yy1300326388** [comment]
iOS  远端依赖未更新，暂时不做处理
https://github.com/CocoaPods/Specs/tree/master/Specs/d/9/8/Ads-CN

**Comment by yy1300326388** [comment]
Android 远程依赖已更新，等待 iOS 更新

**Comment by cunwaitaoshu** [comment]
> Android 远程依赖已更新，等待 iOS 更新

ios也更新了

**Comment by yy1300326388** [comment]
iOS 已完成开发，预计本周末可以测试完毕并升级一个新版本

**Comment by cunwaitaoshu** [comment]
辛苦了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月26日(星期五) 晚上10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FlutterAds/flutter_pangle_ads] 穿山甲SDK4700版本开屏广告接入方式变更 (Issue #30)





 
iOS 已完成开发，预计本周末可以测试完毕并升级一个新版本

**Comment by yy1300326388** [comment]
@mifeng9999 @cunwaitaoshu 

`v2.6.0` 版本已更新：https://pub.dev/packages/flutter_pangle_ads
