### ISSUE TITLE
激励视频需要支持二次激励

### ISSUE THREAD

**Issue by daixianceng** [FlutterAds/flutter_pangle_ads#31]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/6077236/180757250-b1dc1563-3a9c-4f57-bb18-b6548a468a17.png">

**Comment by yy1300326388** [comment]
收到

**Comment by yy1300326388** [comment]
@daixianceng  4700 已支持，在路上了

**Comment by yy1300326388** [comment]
相关官方文档：
https://www.csjplatform.com/supportcenter/26221
https://www.csjplatform.com/supportcenter/5399

**Comment by yy1300326388** [comment]
进阶奖励穿山甲返回的 rewardType 也是 0，需要自己判断一下逻辑

**Comment by yy1300326388** [comment]
`v2.6.0` 版本已更新：https://pub.dev/packages/flutter_pangle_ads
