### ISSUE TITLE
激励广告展示失败，但是没有错误码

### ISSUE THREAD

**Issue by sunjianan9900** [FlutterAds/flutter_pangle_ads#36]
1、使用的是测试app、测试激励视频广告、ios模拟器
2、其他广告已正常显示：开屏、banner
3、flutter 3.3 ， flutter_pangle_ads 2.6.1 ， SDK版本号 - Ads-CN (4.7.1.0)、macos 12.5.1
4、输出:

-[RewardVideoPage nativeExpressRewardedVideoAd:didFailWithError:]

![image](https://user-images.githubusercontent.com/10936316/189574363-d5c586cb-215f-4cd7-8e83-d4d94351349a.png)

请问下，为什么激励视频广告展示不出来，然后控制台打印不出来error code

**Comment by sunjianan9900** [comment]
只传入了广告位id，广告设置的不使用服务器验证
 FlutterPangleAds.showRewardVideoAd(
                          Config.rwAd,
                        );

**Comment by sunjianan9900** [comment]
[FullScreenVideoPage nativeExpressFullscreenVideoAd:didFailWithError:]

新版插屏也这样，好像是有视频就会这样？

**Comment by sunjianan9900** [comment]
使用DEMO给的应用ID和广告位ID，可以正常拉取广告了
难道是新建的广告位要等一段时间才能拉到吗

**Comment by SheepYang1993** [comment]
请问最后是怎么解决的？

**Comment by BytesZero** [comment]
新建的广告位需要等待 30～120 分钟后再请求广告
