### ISSUE TITLE
由于网络延迟导致开屏空白

### ISSUE THREAD

**Issue by PrideMe** [FlutterAds/flutter_pangle_ads#37]
我本机运行项目，发现会有短暂的空白，这个应该是网络请求引起的，这种情况如何解决

**Comment by PrideMe** [comment]
![image](https://user-images.githubusercontent.com/19489612/189803086-cf807568-3062-4d0c-a202-bea11ba163a9.png)

**Comment by PrideMe** [comment]
https://user-images.githubusercontent.com/19489612/189803198-a285c7f3-77a2-402b-83a5-abef2a53f4c3.MOV

**Comment by PrideMe** [comment]
https://user-images.githubusercontent.com/19489612/189803664-95b498d6-1dcc-4c47-84ae-8ed25251ae3b.MOV

**Comment by PrideMe** [comment]
是不是可以加一个监听

**Comment by yy1300326388** [comment]
你没有配置启动也而已

**Comment by PrideMe** [comment]
这就不明白了，原项目也没配置吗？我看在xcode是有的，而且逐帧看的话，是从有到无的过程。
这个是下载的您的原工程直接跑的 > 你没有配置启动也而已

**Comment by PrideMe** [comment]
> 你没有配置启动也而已

原项目也没配置吗？我看在xcode是有的，而且逐帧看的话，是从有到无的过程。
这个是下载的您的原工程直接跑的

**Comment by PrideMe** [comment]
我就是直接运行的本工程，没做什么修改
