### ISSUE TITLE
请更新 iOS 16 适配SDK

### ISSUE THREAD

**Issue by nne998** [FlutterAds/flutter_pangle_ads#38]
官方已经放出了ios16适配的版本 4.7.1.1，解决闪退问题

**Comment by nne998** [comment]
![WX20220915-143138@2x](https://user-images.githubusercontent.com/148901/190331060-22f58133-386b-4fdc-b642-8ca2e2ea24a5.png)

**Comment by nne998** [comment]
已提交PR

**Comment by yy1300326388** [comment]
等待官方升级或自行升级 SDK，[参考文档说明](https://github.com/FlutterAds/flutter_pangle_ads#%E5%8E%9F%E7%94%9F-sdk-%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%96%B9%E6%B3%95)
