### ISSUE TITLE
从后台切换会前台,调用开屏广告会有空白.

### ISSUE THREAD

**Issue by KeyX-y** [FlutterAds/flutter_pangle_ads#41]
前提已经配置启动页
app冷启动时,显示启动页,展示广告,没有白屏;
 **但是从app从前台切换回后台, 再从后台切换回前台时调用开屏广告api,这时候会有一个白屏. 等广告返回的时候,页面展示广告了,**

作者可以提供一个展示启动页的api,这个问题就可以解决

**Comment by yy1300326388** [comment]
有开屏页面的 api
