### ISSUE TITLE
sdk2.6.1: Ads-CN会默认最高级5.0.x.x，继而无法编译成功

### ISSUE THREAD

**Issue by gaishixiaogui** [FlutterAds/flutter_pangle_ads#47]
报错详情：
Generics Issue (Xcode): No type or protocol named 'BUNativeExpresInterstitialAdDelegate'
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_pangle_ads-2.6.1/ios/Classes/Page/InterstitialPage.h:10:41

Semantic Issue (Xcode): Unknown type name 'BUNativeExpressInterstitialAd'
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_pangle_ads-2.6.1/ios/Classes/Page/InterstitialPage.h:11:30

Semantic Issue (Xcode): Property with 'retain (or strong)' attribute must be of object type
/Users/xxx/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_pangle_ads-2.6.1/ios/Classes/Page/InterstitialPage.h:11:0

目前的解决办法：
在Podfile.lock中把Ads-CN和Ads-CN/BUAdSDK手动改为4.8.1.1，
然后pod install，会提示其他的插件版本对不上，对应去一个一个按提示改，直到pod install成功就能打包安装了。

可能需要作者大大解决的：
插件对应的原生sdk是不是默认最高级了呀，应该写死当前flutter插件对应的原生插件版本吗？
或者，啥时候对应更新下原生插件等级对应的flutter插件～

**Comment by yy1300326388** [comment]
自己指定一下版本

**Comment by yy1300326388** [comment]
更新中

**Comment by yy1300326388** [comment]
已更新，请升级到 `2.7.0` 版本 ：https://pub.dev/packages/flutter_pangle_ads
