### ISSUE TITLE
安卓和IOS的SDK版本该更新了

### ISSUE THREAD

**Issue by ZKXSparke** [FlutterAds/flutter_pangle_ads#48]
现在最新的是5.0.0.4，新版本IOS还存在破坏性变更，希望及时更新

**Comment by yy1300326388** [comment]
感谢提醒，近期

**Comment by ZKXSparke** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by propertyabc** [comment]
IOS 不正常了，辛苦修复一下吧 @yy1300326388 
No type or protocol named 'BUNativeExpresInterstitialAdDelegate'
Unknown type name 'BUNativeExpressInterstitialAd'
 Property with 'retain (or strong)' attribute must be of object type

**Comment by ZKXSparke** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yy1300326388** [comment]
更新中

**Comment by yy1300326388** [comment]
关注 https://github.com/FlutterAds/flutter_pangle_ads/issues/47
