### ISSUE TITLE
信息流视频广告滑动后会在左上角出现小窗播放

### ISSUE THREAD

**Issue by ZKXSparke** [FlutterAds/flutter_pangle_ads#49]
信息流视频广告滑动后会在左上角出现小窗播放，这个关也关不掉，而且还有点击事件穿透，比较影响体验，希望解决

**Comment by ZKXSparke** [comment]
补充一下，好像只在Android出现这个bug，ios没有这个现象

**Comment by yy1300326388** [comment]
已更新 [v2.8.0](https://github.com/FlutterAds/flutter_pangle_ads/releases)
