### ISSUE TITLE
【穿山甲官方】接入文档和错误码列表

### ISSUE THREAD

**Issue by yy1300326388** [FlutterAds/flutter_pangle_ads#5]
##【穿山甲官方】接入文档和错误码列表
### 接入文档
- [Android](https://www.pangle.cn/support/doc/5fcc8ef7253fee000ed14efa)
- [iOS](https://www.pangle.cn/support/doc/5fbdb5e11ee5c2001d3f0c75)

### 常见错误码
- [Android](https://www.pangle.cn/support/doc/5fcc8fbc253fee000ed14f2d)
- [iOS](https://www.pangle.cn/support/doc/5fbdb67b1ee5c2001d3f0ca1)
- [错误码列表](https://developers.adnet.qq.com/doc/ios/union/union_debug#%E9%94%99%E8%AF%AF%E7%A0%81)

如果遇到问题可以先看 Log ，然后根据错误码排查常见错误

> 用心开源 | 感谢有你 | 感谢 Star

**Comment by yy1300326388** [comment]
开源不易，感谢支持，你的 `Star` 就是我的动力

**Comment by Miaoyu0914** [comment]
接入flutter_pangle_ads: ^2.7.0时进行编译报以下错误：Duplicate class com.bytedance.sdk.openadsdk.AdSlot found in modules jetified-ads-sdk-5.1.1.1-runtime (com.pangle.global:ads-sdk:5.1.1.1) and jetified-ads-sdk-pro-5.1.0.2-runtime (com.pangle.cn:ads-sdk-pro:5.1.0.2)，希望能得到回复

**Comment by xyxStyle** [comment]
麻烦问下海外的版本需要如何配置呢

**Comment by yy1300326388** [comment]
> 麻烦问下海外的版本需要如何配置呢

海外版自行修改依赖即可
