### ISSUE TITLE
激励视频广告怎么随时手动可触发立即退出关闭广告

### ISSUE THREAD

**Issue by sven-xie** [FlutterAds/flutter_pangle_ads#53]
激励视频广告怎么随时手动可触发立即退出关闭广告，比如不想要获得激励，想要立即退出关闭广告，这个关闭怎么配置支持？

**Comment by yy1300326388** [comment]
目前没有办法

**Comment by sven-xie** [comment]
苹果和华为商店审核，要求激励广告视频，需要有手动退出关闭的入口，希望后续版本可以增加支持，感谢

**Comment by yy1300326388** [comment]
这个你需要询问穿山甲平台或后台配置，不是插件层来解决的
