### ISSUE TITLE
Remove not allowed permissions

### ISSUE THREAD

**Issue by marcellocamara** [FlutterAds/flutter_pangle_ads#55]
Hello, I was trying to use this lib on flutter, and when I released my appbundle into the Play Console I've received two errors about the denied permissions REQUEST_INSTALL_PACKAGES and QUERY_ALL_PACKAGES. And I can't publish the app without removing this permissions.

https://github.com/FlutterAds/flutter_pangle_ads/blob/develop/android/src/main/AndroidManifest.xml#L18

They cannot be on the libs anymore, due to Google's policy

Reference: https://support.google.com/googleplay/android-developer/answer/12085295

**Comment by yy1300326388** [comment]
@marcellocamara 

你可以这样配置你的 `android/app/src/main/AndroidManifest.xml` 文件即可

```
<uses-permission android:name="android.permission. REQUEST_INSTALL_PACKAGES" tools:node="remove"/>
<uses-permission android:name="android.permission. QUERY_ALL_PACKAGES" tools:node="remove"/>
```

**Comment by marcellocamara** [comment]
> ```
> <uses-permission android:name="android.permission. REQUEST_INSTALL_PACKAGES" tools:node="remove"/>
> <uses-permission android:name="android.permission. QUERY_ALL_PACKAGES" tools:node="remove"/>
> ```

Yes, It should work.
But the best choice is remove it from the source code (this flutter package). It's legacy and not allowed.

Just opened this issue to warning about it. Maybe some peoples will fall in the same problem and can't use this package.

In my case, I was only linking the Pangle mediation. I do not intend to load ads directly from Pangle, using their own banners. 
I resolved it on the android native side, build.gradle file, only adding the sdk and the maven link.

**Comment by yy1300326388** [comment]
首先感谢你的反馈
我不会删除它，因为删除它可能会影响你广告的转化，从而你的 eCPM 就会降低，影响广告价值
