### ISSUE TITLE
Error add pangle

### ISSUE THREAD

**Issue by alexfernandojs** [FlutterAds/flutter_pangle_ads#56]
I/Zeus/install_pangle(22695): Plugin INSTALL_FAILEDcom.byted.pangle:5102
W/Zeus/install_pangle(22695): Plugin delete file by failedCount > 0 com.byted.pangle:5102
D/TTPluginManager(22695): Install dl plugin com.byted.pangle failed, need notify: false
W/Zeus/load_pangle(22695): PluginLoader loadPlugin, UN_INSTALLED, com.byted.pangle

**Comment by yy1300326388** [comment]
已更新 [v2.8.0](https://github.com/FlutterAds/flutter_pangle_ads/releases)
