### ISSUE TITLE
ios 模拟器 ios 16 请求IDFA闪退

### ISSUE THREAD

**Issue by Crazz-Joe** [FlutterAds/flutter_pangle_ads#58]
ios 模拟器 ios 16 请求IDFA闪退  

FlutterPangleAds.requestIDFA

**Comment by gaishixiaogui** [comment]
@hhgz9527 我的是在ios16.3.1版本后，请求IDFA无效，手机并不会弹出TrackingUsageDescription的弹窗，大佬要更新插件了吗！！

**Comment by yy1300326388** [comment]
@Crazz-Joe 你是否添加了权限呢？可以将错误日志发一下吗？跑 Demo 是否可以呢？

**Comment by yy1300326388** [comment]
@gaishixiaogui 只有首次会弹出，卸载重新看看

**Comment by Crazz-Joe** [comment]
> @Crazz-Joe 你是否添加了权限呢？可以将错误日志发一下吗？跑 Demo 是否可以呢？

对不起，大佬，是我info.plist忘记加权限配置了😭
