### ISSUE TITLE
请问作者插件是如何发布到 pub 的，我发布总是报错

### ISSUE THREAD

**Issue by gege66** [FlutterAds/flutter_pangle_ads#6]
如题

**Comment by yy1300326388** [comment]
我也遇到过多次发布到pub 失败的情况，建议检查网络是否可以访问google.com，终端和浏览器有些不同，请给终端也设置代理。

最后我发现即使我设置了代理，有些时候终端代理也非常不稳定，我现在使用的是 GitHub Action  来实现自动发布的，具体参考我的这个配置文件[.github/workflows/publish.yml](https://github.com/FlutterAds/flutter_pangle_ads/blob/develop/.github/workflows/publish.yml)

**Comment by yy1300326388** [comment]
如继续有问题可以联系我重新开启
