### ISSUE TITLE
banner广告的神奇！！！

### ISSUE THREAD

**Issue by wolf-leo** [FlutterAds/flutter_pangle_ads#60]
安卓 插件最新
首页使用 banner广告
然后其他任何页面这个广告都会跟着出现！！！

![微信图片_20230324104811](https://user-images.githubusercontent.com/37436228/227411635-8a2020b6-7ee6-41bd-9707-321ebac96917.jpg)
![微信图片_20230324104300](https://user-images.githubusercontent.com/37436228/227411646-9f6b5f2a-9326-4359-b017-e3fe3970d4a0.jpg)

**Comment by yy1300326388** [comment]
已更新 [v2.8.0](https://github.com/FlutterAds/flutter_pangle_ads/releases)
