### ISSUE TITLE
调用开屏广告时，安卓真机白屏

### ISSUE THREAD

**Issue by gaishixiaogui** [FlutterAds/flutter_pangle_ads#61]
在ios真机和安卓模拟器是ok的，
安卓调用广告时直接白屏，无法再做任何操作。可以复现，安卓10以下的手机必现。

编译环境
Flutter 3.7.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90c64ed42b (13 days ago) • 2023-03-21 11:27:08 -0500
Engine • revision 9aa7816315
Tools • Dart 2.19.5 • DevTools 2.20.1
硬件环境
Apple M1/MacOS 13.2 (22D49)

![image](https://user-images.githubusercontent.com/61375126/229683993-4be5ac0f-6c19-4798-9b03-1fed17223101.png)
![image](https://user-images.githubusercontent.com/61375126/229684003-782caa65-bd98-4d39-8033-18ff085934ef.png)

此外上个月安卓用户请求feed流广告时会闪退，当时我已经拿掉了。。

**Comment by yy1300326388** [comment]
此广告插件中，没有什么 MainController ,应该是你自己的代码，所以不做处理，可以加我微信单独付费解决哈
toponelan
