### ISSUE TITLE
安卓端显示banner 如果广告类型是视频画面错位异常；

### ISSUE THREAD

**Issue by sven-xie** [FlutterAds/flutter_pangle_ads#64]
安卓端显示600*500 banner 如果广告类型是视频类型，画面显示错位异常；

正确的广告位置应该是页面底部，但是广告画面跑到页面顶部，顶部显示的视频不可点击；

![Screenshot_2023-04-23-17-25-22-93_1f9530664892eb3](https://user-images.githubusercontent.com/13388790/233882447-ce7ff34e-fdcd-4bf6-9a96-bfbefabd7d1f.jpg)

**Comment by kingrmb** [comment]
也遇到这个问题了，辛苦修复一下吧 @sven-xie @hhgz9527 @yy1300326388 
flutter_pangle_ads: ^2.7.0

**Comment by yy1300326388** [comment]
已更新 [v2.8.0](https://github.com/FlutterAds/flutter_pangle_ads/releases)
