### ISSUE TITLE
信息流广告错位

### ISSUE THREAD

**Issue by gaoqingiOS** [FlutterAds/flutter_pangle_ads#65]

**Comment by gaoqingiOS** [comment]
![image](https://user-images.githubusercontent.com/13009419/235303985-b0dc9435-4f22-42f3-9708-e512679a1126.png)

**Comment by SnaChat** [comment]
我也遇到这个Bug，头疼，这个发生的概率蛮大的

**Comment by yy1300326388** [comment]
升级到新版本试试 已更新 [v2.8.0](https://github.com/FlutterAds/flutter_pangle_ads/releases)
