### ISSUE TITLE
有新版本了，大佬什么时候升级

### ISSUE THREAD

**Issue by liaovoid** [FlutterAds/flutter_pangle_ads#68]
文档版本 | 修订日期 | 修订说明
-- | -- | --
5.4.0.3 | 2023-06-09 | 【优化】原生动态化及新插屏广告样式；【优化】激励视频互动挽留弹窗样式；【修复】已知问题；
5.3.0.5 | 2023-05-11 | 【重要提醒】v>=5.3.0.0，需严格按照接入规范注册激励视频和全屏视频广告监听，在获取到TTRewardVideoAd/TTFullScreenVideoAd对象之后，调用showRewardVideo/showFullScreenVideo展示广告之前，调用setAdInteractionListener设置交互监听器以及其他监听器；【修复】已知问题；
5.3.0.3 | 2023-04-26 | 【新增】基于用户/请求粒度回传奖励物和奖励数值，提升用户对奖励的感知和观看时长，从而提升收入；【优化】下载类样式与下载链路；【优化】渲染引擎性能；【修复】已知问题；
5.2.0.5 | 2023-03-20 | 【优化】draw流支持动态布局模板展示&样式优化；【优化】激励视频样式及轻互动预算优化；【修复】draw视频信息流播放重音问题；
5.1.0.2 | 2023-01-13 | 【新增】自渲染信息流ComplianceInfo类中新增权限列表URL的获取接口；【重要变更】onDislikeEvent等相关功能实现&NativeAdType的get和set方法标记废弃；【优化】电商聚合页样式优化；【优化】激励广告埋点上报；【修复】已知问题；
5.0.0.4 | 2022-12-21 | 【修复】已知问题；【优化】去除无效日志打印；

**Comment by yy1300326388** [comment]
@liaovoid  已更新 [v2.8.0](https://github.com/FlutterAds/flutter_pangle_ads/releases)
