### ISSUE TITLE
字节跳动存在违规收集Androidid

### ISSUE THREAD

**Issue by zzg19901210** [FlutterAds/flutter_pangle_ads#69]
APP未见向用户明示 com.bytedance. SDK收集使用个人信息的目的、方式和范围，未经用户同意，SDK存在收集“Android id等”的行为。

**Comment by yy1300326388** [comment]
这个需要你自己从初始化的时机角度去解决。和 sdk 关系不大

**Comment by winter-tech** [comment]
我也遇到了，小米应用商店的隐私检测，我都没有调用初始化方法，只是引入了依赖包，也会提示这个。
