### ISSUE TITLE
激励视频展示完没有销毁对象，导致后面展示重复的广告

### ISSUE THREAD

**Issue by zytabcd123** [FlutterAds/flutter_pangle_ads#7]
![image](https://user-images.githubusercontent.com/11885452/133022638-0dad441b-c11e-4844-b5b8-6359a5f97336.png)

**Comment by yy1300326388** [comment]
收到，我测试后优化一下

**Comment by zytabcd123** [comment]
谢谢，我刚刚测试了你的Android demo看了5个激励视频都是一个广告。

**Comment by yy1300326388** [comment]
@zytabcd123  我测试了把激励视频广告对象值为空依然是会有重复的广告呢，我这里的广告位是测试id，你接入正式的试试看。

**Comment by yy1300326388** [comment]
我加到下个版本中看看实际是否可以缓解

**Comment by zytabcd123** [comment]
我正式广告位测试了已经好了，不会出现重复的广告了

**Comment by yy1300326388** [comment]
@zytabcd123  收到，那我先关闭了，有任何问题请联系我
