### ISSUE TITLE
网络拉取广告资源失败，导致广告初始化失败，有API可以拿到结果吗？这样页面不进行展示

### ISSUE THREAD

**Issue by kingrmb** [FlutterAds/flutter_pangle_ads#71]
拿到结果不展示，页面就不会空白一块

**Comment by yy1300326388** [comment]
提供一下视频和版本信息，还有日志

**Comment by kingrmb** [comment]
网络稍差的情况，就会拉取广告失败的，辛苦看看能不能支持一下体验升级 ---- 回复的原邮件 ***@***.***>发送日期2023年10月31日 21:11 ***@***.***> ***@***.***>***@***.***>主题Re: [FlutterAds/flutter_pangle_ads] 网络拉取广告资源失败，导致广告初始化失败，有API可以拿到结果吗？这样页面不进行展示 (Issue #71)
提供一下视频和版本信息，还有日志

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/FlutterAds/flutter_pangle_ads/issues/71#issuecomment-1787191288",
"url": "https://github.com/FlutterAds/flutter_pangle_ads/issues/71#issuecomment-1787191288",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BytesZero** [comment]
这个情况需要自己去优化或付费提出优化需求
