### ISSUE TITLE
RewardVideoPage nativeExpressRewardedVideoAd:didFailWithError:

### ISSUE THREAD

**Issue by SheepYang1993** [FlutterAds/flutter_pangle_ads#72]
RewardVideoPage nativeExpressRewardedVideoAd:didFailWithError:
只有这个提示，没有更多的信息了

**Comment by BytesZero** [comment]
你输入一下详细版本信息和日志

**Comment by BingKui** [comment]
我也是这个问题，flutter 3.13.8 xcode 15.0.1

**Comment by BingKui** [comment]
Performing hot restart...
Restarted application in 387ms.
initAd:YES
requestIDFA:NO
-[SplashViewController splashAdLoadFail:error:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]
-[AdBannerView nativeExpressBannerAdView:didLoadFailWithError:]

**Comment by BytesZero** [comment]
是不是 ios17 系统
