### ISSUE TITLE
ios 信息流设计存在问题

### ISSUE THREAD

**Issue by matrixclark** [FlutterAds/flutter_pangle_ads#73]
```
// 加载信息流广告
- (void) loadFeedAd:(FlutterMethodCall*) call result:(FlutterResult) result{
    self.fad=[[FeedAdLoad alloc] init];
    [self.fad loadFeedAdList:call result:result eventSink:self.eventSink];
}
```
每次加载信息流都是生成一个新的 FeedAdLoad，  如果 一个界面里连续加载。 前面生成的 FeedAdLoad 不会被 retain了， 就被释放，出现的情况就是前面生成的 AdFeedView  的delegate 没了。  回调信息都接收不到。点击关闭不会有回调，不会移除。 点击消息也不能回传给 Flutter .
但如果不生成新的 FeedAdLoad，  不同的 slotId 不创建新的实例也不行。    我对Flutter 不熟，第一次研究插件，感觉目前这一块设计存在很多问题。 不知道如何解决。

**Comment by BytesZero** [comment]
Flutter 中的 FeedView 有 keeplive 属性来保持这种情况，所以可以保证不销毁掉，我做过长列表的测试，没问题的

**Comment by BytesZero** [comment]
不要感觉，先运行起来看看就明白了
