### ISSUE TITLE
激励视频广告，没有马上展示“关闭“按钮，华为等平台没法上架

### ISSUE THREAD

**Issue by SnaChat** [FlutterAds/flutter_pangle_ads#74]
每次加载激励视频，都是过几秒才出现这个跳过按钮，华为那边的审核要求是用户，点进去马上就能”跳过“的选项
![2571705498803_ pic](https://github.com/FlutterAds/flutter_pangle_ads/assets/17908675/0eaa6dc2-13da-4f28-9a54-4fcd4e6683a1)

![2581705498805_ pic](https://github.com/FlutterAds/flutter_pangle_ads/assets/17908675/1bd31881-2ce9-454e-a232-a9c03c15fabd)

华为审核的回复：
<img width="725" alt="截屏2024-01-17 21 36 47" src="https://github.com/FlutterAds/flutter_pangle_ads/assets/17908675/8e4ce7ef-90bd-426d-9288-f4e2aac85583">

还有一个建议，信息流视频，关闭的按钮（就那个小 "x"） ,要是展示”反馈“，华为也会审核不通过。尽量用小 "x"。
![Uploading 2591705499215_.pic.jpg…]()

**Comment by SnaChat** [comment]
希望得到回复，或者优化，或者解决方案！其他应用平台都没问题，能正常上架

**Comment by BytesZero** [comment]
@SnaChat 这种情况联系穿山甲平台客服进行处理。

**Comment by SnaChat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SnaChat** [comment]
好的，感谢！！！还有一个问题哈，就是信息流广告这一块，根据穿山甲后台的宽高比，用屏幕宽度+前面那个宽高比列，动态计算高度，但是最后广告的展示上还是不是特别的完美，这个也是穿山甲那边广告问题吗？这个有点印象用户体验，banner广告效果就好很多！

**Comment by BytesZero** [comment]
这个动态高度有一定的问题，闪屏卡顿，所以需要是固定比例的，所有代码位都是固定比例，代码中也是一样
