### ISSUE TITLE
 目前android的sdk v5.5 貌似不正常

### ISSUE THREAD

**Issue by nne998** [FlutterAds/flutter_pangle_ads#76]
官方的sdk已经升到 v5.9+ ，  目前android的sdk v5.5 貌似不正常

谢谢

**Comment by BytesZero** [comment]
@nne998 开源版本，如下原因更新比较慢：
- 由于官方现在也已转向维护 GroMore SDK 了
- 个人精力有限，主要服务 Pro 版本客户

了解 GoMore  Pro 版本看这里： https://flutterads.github.io/site
